
[build]
  # Build command to install dependencies
  command = "pip install -r netlify/functions/requirements.txt"
  # Publish static files
  publish = "static"

[build.environment]
  # Python version
  PYTHON_VERSION = "3.10.5"
  # Ensure pip is up to date
  PIP_VERSION = "23.1.2"


# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/generate_design"
  to = "/.netlify/functions/generate_design"
  status = 200

[[redirects]]
  from = "/api/generate_floor_plan"
  to = "/.netlify/functions/generate_floor_plan"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self';"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables (these will be set in Netlify dashboard)
# FLASK_ENV = "production"
# SECRET_KEY = "your-production-secret-key"
